mod 'cargomedia/cm',
  :git => 'git@github.com:cargomedia/puppet-cm.git'

mod 'cargomedia/environment',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/environment'

mod 'cargomedia/truecrypt',
  :git => 'git@github.com:cargomedia/puppet-packages.git',
  :path => 'modules/truecrypt'
